meta:
  model_name: deit_small
  master_port: 8888
  load_checkpoint: false
  training: true
  copy_data: false
  device: cuda:0
data:
  root_path: mtproject/datasets01/
  image_folder: Alzheimers/
  num_classes: 4
optimization:
  weight_decay: 0.0
  lr: 6.4
  epochs: 100
  num_blocks: 1
  normalize: true
logging:
  folder: mtproject/checkpoint/msn_logs/
  write_tag: msn-lineval-experiment-1
  pretrain_path: /kaggle/input/epoch200msn/pytorch/zip200ep/1/
